In [1]:
import pandas as pd

s0 = pd.read_csv("./../results_realcause/bpic2012/val/generated_data/bpic2012_sample0.csv")
s0

,preds_clf,probs_clf_0,probs_clf_1,y_pred_set_0.1_clf,y_pred_set_0.2_clf,y_pred_set_0.3_clf,y_pred_set_0.4_clf,y_pred_set_0.5_clf,y_pred_set_0.6_clf,y_pred_set_0.7_clf,...,y_upper_0.8_reg,y_lower_0.9_reg,y_upper_0.9_reg,prefix_nr,case_length,t,y,y0,y1,ite
0,0,0.999912,0.000088,0,0,0,0,0,0,0,...,10.345306,2.443308,9.339634,1,4,1.0,0.117763,0.000000,0.117763,0.117763
1,0,0.999912,0.000088,0,0,0,0,0,0,0,...,10.313726,2.515945,9.266997,2,4,1.0,0.773442,0.158973,0.773442,0.614469
2,0,0.999912,0.000088,0,0,0,0,0,0,0,...,10.345306,2.443308,9.339634,3,4,0.0,0.123123,0.123123,0.000000,-0.123123
3,0,0.999906,0.000094,0,0,0,0,0,0,0,...,10.354546,2.515945,9.266997,1,3,1.0,0.747661,0.174425,0.747661,0.573236
4,0,0.999902,0.000098,0,0,0,0,0,0,0,...,10.354882,2.337238,9.445704,2,3,0.0,0.000000,0.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40859,1,0.089071,0.910929,1,1,1,1,1,1,1,...,21.040067,11.717510,17.816397,16,20,1.0,0.720296,0.000000,0.720296,0.720296
40860,1,0.116303,0.883697,1,1,1,1,1,1,1,...,20.831109,10.746601,18.573292,17,20,0.0,0.008537,0.008537,0.000000,-0.008537
40861,1,0.366611,0.633389,1,1,1,1,1,0,0,...,20.101513,11.068199,18.404589,18,20,1.0,0.795863,0.000000,0.795863,0.795863
40862,1,0.193007,0.806993,1,1,1,1,1,1,0,...,20.990953,11.644580,17.596322,19,20,1.0,0.452651,0.115299,0.452651,0.337352
40863,1,0.127924,0.872076,1,1,1,1,1,1,1,...,20.159647,12.685398,16.763205,20,20,1.0,1.000000,0.000000,1.000000,1.000000

In [12]:
import pandas as pd
import numpy as np
import sys
sys.path.append('/home/mshoush/5th/common_files') 
from DatasetManager import DatasetManager

task_type = "classification"
cls_method_all = "catboost"
dataset_name = "bpic2012"
cls_encoding = "agg"

cls_method = "catboost"


dataset_manager = DatasetManager(dataset_name, task_type)

data_type = "val"
dataset_name = "bpic2012"
results_dir = f"./../results_all/online/{data_type}/{dataset_name}/"
data_dir = f"/home/mshoush/5th/results_all/predictive/{dataset_name}/{data_type}/"  
file_name = f"{data_type}_xgboost_combined_{dataset_name}.parquet"

train = pd.read_parquet(data_dir + file_name)
#train['Treatment1'] = np.where(train['Treatment1'] == "Treatment", 1, 0)
cat_feat_idx = np.where((train.dtypes == 'object') & ~train.columns.isin([str(dataset_manager.label_col), "Treatment"]))[0]
train

,actual_clf,preds_clf,probs_clf_0,probs_clf_1,y_pred_set_0.1_clf,y_pred_set_0.2_clf,y_pred_set_0.3_clf,y_pred_set_0.4_clf,y_pred_set_0.5_clf,y_pred_set_0.6_clf,...,y_lower_0.8_reg,y_upper_0.8_reg,y_lower_0.9_reg,y_upper_0.9_reg,prefix_nr,case_length,case_id,activity,timestamp,Treatment1
0,0,0,0.999912,0.000088,0,0,0,0,0,0,...,1.437636,10.345306,2.443308,9.339634,1,4,193440,A_SUBMITTED,2011-12-14 10:01:12.354,0
1,0,0,0.999912,0.000088,0,0,0,0,0,0,...,1.469215,10.313726,2.515945,9.266997,2,4,193440,A_PARTLYSUBMITTED,2011-12-14 10:01:14.720,0
2,0,0,0.999912,0.000088,0,0,0,0,0,0,...,1.437636,10.345306,2.443308,9.339634,3,4,193440,W_Afhandelen leads,2011-12-14 10:03:51.474,0
3,0,0,0.999906,0.000094,0,0,0,0,0,0,...,1.428396,10.354546,2.515945,9.266997,1,3,193443,A_SUBMITTED,2011-12-14 10:14:39.517,0
4,0,0,0.999902,0.000098,0,0,0,0,0,0,...,1.428060,10.354882,2.337238,9.445704,2,3,193443,A_PARTLYSUBMITTED,2011-12-14 10:14:39.692,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40859,0,1,0.089071,0.910929,1,1,1,1,1,1,...,8.493840,21.040067,11.717510,17.816397,16,20,205256,W_Nabellen offertes,2012-03-03 15:06:47.226,1
40860,0,1,0.116303,0.883697,1,1,1,1,1,1,...,8.488784,20.831109,10.746601,18.573292,17,20,205256,W_Nabellen offertes,2012-03-08 14:55:00.554,1
40861,0,1,0.366611,0.633389,1,1,1,1,1,0,...,9.371275,20.101513,11.068199,18.404589,18,20,205256,W_Nabellen offertes,2012-03-09 16:19:14.663,1
40862,0,1,0.193007,0.806993,1,1,1,1,1,1,...,8.249949,20.990953,11.644580,17.596322,19,20,205256,W_Nabellen offertes,2012-03-09 16:19:53.248,1
40863,0,1,0.127924,0.872076,1,1,1,1,1,1,...,9.288956,20.159647,12.685398,16.763205,20,20,205256,W_Nabellen offertes,2012-03-12 08:15:13.658,1

In [13]:
cat_feat_idx

array([35, 36])

In [5]:
if cls_method=="catboost":
    columns_to_dummify = cat_feat_idx
    train.iloc[:, columns_to_dummify] = train.iloc[:, columns_to_dummify].apply(lambda x: x.astype("category").cat.codes)
    
train

,amount_req,case_length,Total_Offers,event,activity,resource,event_nr_mean,event_nr_max,event_nr_min,event_nr_sum,...,case_completion_rate_min,case_completion_rate_sum,case_completion_rate_std,elapsed_mean,elapsed_max,elapsed_min,elapsed_sum,elapsed_std,label,Treatment
0,20000.0,18,1.0,0.0,0,0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1,1
1,5000.0,20,2.0,0.0,0,0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1,1
2,7000.0,20,3.0,0.0,0,0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1,1
3,15000.0,3,0.0,1.0,0,0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1,1
4,5000.0,3,0.0,1.0,0,0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65109,15000.0,20,1.0,0.0,5,24,10.5,20.0,1.0,210.0,...,0.0,0.0,0.0,4.624941,13.593297,0.0,92.498830,5.709643,0,0
65110,12000.0,20,1.0,1.0,5,47,10.5,20.0,1.0,210.0,...,0.0,0.0,0.0,2.858396,6.760718,0.0,57.167924,3.140798,0,0
65111,25000.0,20,2.0,0.0,4,44,10.5,20.0,1.0,210.0,...,0.0,0.0,0.0,4.518519,22.588809,0.0,90.370385,6.475994,0,0
65112,10000.0,20,1.0,0.0,5,25,10.5,20.0,1.0,210.0,...,0.0,0.0,0.0,9.732418,22.098934,0.0,194.648350,10.246607,0,0
65113,25000.0,20,1.0,0.0,5,52,10.5,20.0,1.0,210.0,...,0.0,0.0,0.0,7.394404,15.117982,0.0,147.888078,7.324606,0,0

In [7]:
train['activity'].unique()

array([0, 1, 2, 3, 4, 5], dtype=object)